DROP TABLE IF EXISTS article;
	
CREATE TABLE article (
	  id INT AUTO_INCREMENT,
	  slug VARCHAR(1000) UNIQUE NOT NULL,
	  title VARCHAR(1000) NOT NULL,
	  description VARCHAR(1500) NOT NULL,
	  body VARCHAR(15000) NOT NULL,
	  createdAt timestamp DEFAULT CURRENT_TIMESTAMP,
	  updatedAt timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);